name: Dev - Smoke Test

on:
  workflow_dispatch:

jobs:
  deploy-nodejs-app-dev:
    name: Smoke Test Development
    runs-on: ubuntu-latest
    environment: Development
    env:
      TESTIM_TEST_PLAN: Development - Customer Portal - Smoke Tests
    steps:
    - uses: actions/checkout@v2

    - name: Run automation tests
      run: |
        npm i -g @testim/testim-cli
        testim --token "${{ secrets.TESTIM_TOKEN }}" --project "${{ secrets.TESTIM_PROJECT }}" --grid "Testim-Grid" --test-plan "${{ env.TESTIM_TEST_PLAN }}"